### ISSUE TITLE
Floating point numbers don't get parsed correctly

### ISSUE THREAD

**Issue by federicomrc** [Keflon/FunctionZero.ExpressionParserZero#5]
As stated by the title floating point numbers don't get parsed correctly. For instance
`var binding = new ExpressionBind(/*...*/, "0.1"); // Result gives 1 instead of 0.1`
`var binding = new ExpressionBind(/*...*/, "-2.2"); // Result gives -22 instead of -2.2`

**Desktop (please complete the following information):**
 - OS: Win10
 - Version 5.3.1 and last commit (18aed6e)

**Comment by Keflon** [comment]
Thanks for letting me know; I'm not sure how I missed that one! I'll fix that next weekend.

**Comment by Keflon** [comment]
Hi @federicomrc 
I added a couple of unit tests for the above. You'll find them in the latest commit to master ...
```csharp
        [TestMethod]
        public void TestFloatParserExpression()
        {
            var binding = new ExpressionBind(this, "0.1");
            Assert.AreEqual(0.1, (double)binding.Result);
        }

        [TestMethod]
        public void TestNegativeFloatParserExpression()
        {
            var binding = new ExpressionBind(this, "-2.2");
            Assert.AreEqual(-2.2, (double)binding.Result);
        }
```
They both pass; tested in Debug and Release mode.  
Do these tests pass for you?  
If not, or if you are still seeing a problem, please let me know and I'll try to get to the bottom of it.

**Comment by Keflon** [comment]
Closing as cannot repro. Please reopen if you think a problem may exist.
